- alias: Stairway Lights
  trigger:
  - platform: state
    entity_id: binary_sensor.stairway_sensor_sensor
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: group.stairway
  - delay: 00:01:00
  - service: homeassistant.turn_off
    entity_id: group.stairway
  id: '1510605925938'
- alias: Central Heating On
  action:
  - data:
      entity_id: climate.central_heating_system
      temperature: '17.0'
    service: climate.set_temperature
  id: '1510605927115'
  trigger:
  - entity_id: groups.all_devices
    platform: state
    to: home
- alias: Central Heating Off
  action:
  - data:
      entity_id: climate.central_heating_system
      temperature: '14.0'
    service: climate.set_temperature
  id: '1510606757726'
  trigger:
  - entity_id: group.all_devices
    platform: state
    to: not_home
