- alias: Stairway Lights On
  trigger:
  - entity_id: group.stairway
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      brightness: '200'
      entity_id:
      - light.stairway_light_lower
      - light.stairway_light_upper
      transition: '5'
    service: light.turn_on
  id: '1510605925938'
- alias: Central Heating On
  action:
  - data:
      entity_id: climate.central_heating_system
      temperature: '18.5'
    service: climate.set_temperature
  id: '1510605927115'
  trigger:
  - entity_id: group.all_devices
    platform: state
    to: home
- alias: Central Heating Off
  action:
  - data:
      entity_id: climate.central_heating_system
      temperature: '14.0'
    service: climate.set_temperature
  id: '1510606757726'
  trigger:
  - entity_id: group.all_devices
    platform: state
    to: not_home
- action:
  - data:
      entity_id: alarm_control_panel.ha_alarm
    service: alarm_control_panel.alarm_arm_away
  - data:
      entity_id: switch.alarm_keypad_switch
    service: switch.turn_on
  - data:
      message: The alarm is now armed.
    service: notify.garage_speaker
  alias: Alarm to Armed
  condition: []
  id: '1513634400284'
  trigger:
  - entity_id: sensor.alarm_keypad_alarm_level
    from: '0'
    platform: state
    to: '255'
- action:
  - data:
      entity_id: alarm_control_panel.ha_alarm
    service: alarm_control_panel.alarm_disarm
  - data:
      entity_id: switch.alarm_keypad_switch
    service: switch.turn_on
  - data:
      message: The alarm is now set to home.
    service: notify.garage_speaker
  alias: Alarm to Home
  condition: []
  id: '1513671114417'
  trigger:
  - entity_id: sensor.alarm_keypad_alarm_level
    from: '255'
    platform: state
    to: '0'
- action:
  - service: shell_command.set_keypad_away
  - data:
      entity_id: switch.alarm_keypad_switch
    service: switch.turn_on
  alias: Keypad to Armed
  condition: []
  id: '1513678597078'
  trigger:
  - entity_id: alarm_control_panel.ha_alarm
    platform: state
    to: armed_away
- action:
  - service: shell_command.set_keypad_home
  - data:
      entity_id: switch.alarm_keypad_switch
    service: switch.turn_on
  alias: Keypad to Home
  condition: []
  id: '1513678726380'
  trigger:
  - entity_id: alarm_control_panel.ha_alarm
    platform: state
    to: disarmed
- action:
  - data:
      message: The alarm has been triggered. Please disarm
    service: notify.garage_speaker
  alias: Alarm Armed Away to Pending
  condition: []
  id: '1513859469939'
  trigger:
  - entity_id: alarm_control_panel.ha_alarm
    from: armed_away
    platform: state
    to: pending
- action:
  - service: alarm_control_panel.alarm_trigger
  alias: Alarm Sensors Detected Movement
  condition:
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_away
  id: '1513863376692'
  trigger:
  - entity_id: binary_sensor.lounge_sensor_sensor
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.garage_sensor_sensor
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.stairway_sensor_sensor
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      message: The alarm is now sounding.
    service: notify.garage_speaker
  - data:
      entity_id: switch.siren_switch
    service: switch.turn_on
  alias: Alarm Triggered
  condition: []
  id: '1513863573555'
  trigger:
  - entity_id: alarm_control_panel.ha_alarm
    platform: state
    to: triggered
- action:
  - data:
      entity_id: switch.central_heating_switch
    service: switch.toggle
  - delay: 00:00:30
  - data:
      entity_id: switch.central_heating_switch
    service: switch.toggle
  alias: Keep Central Heating Alive
  condition: []
  id: '1517419740700'
  trigger:
  - at: 02:00:00
    platform: time
  - at: 07:00:00
    platform: time
  - at: '12:00:00'
    platform: time
  - at: '17:00:00'
    platform: time
  - at: '22:00:00'
    platform: time
- action:
  - delay: 00:02:00
  - data:
      entity_id: group.stairway
    service: homeassistant.turn_off
  alias: Stairway Lights Off
  condition: []
  id: '1518096751261'
  trigger:
  - entity_id: group.stairway
    platform: state
    to: 'on'
- action:
  - service: notify.lounge_tv
    data:
      message: Heating is ON                                                 CURRENTLY
        {{states.sensor.lounge_sensor_temperature.state}}째C                        SET
        TO {{states.climate.central_heating_system.attributes.temperature}}째C
  alias: Notify Heating On
  condition: []
  id: '1518123382906'
  trigger:
  - entity_id: switch.central_heating_switch
    from: 'off'
    platform: state
    to: 'on'
- action:
  - service: notify.lounge_tv
    data:
      message: Heating is OFF                                                CURRENTLY
        {{states.sensor.lounge_sensor_temperature.state}}째C                        SET
        TO {{states.climate.central_heating_system.attributes.temperature}}째C
  alias: Notify Heating Off
  condition: []
  id: '1518130456888'
  trigger:
  - entity_id: switch.central_heating_switch
    from: 'on'
    platform: state
    to: 'off'
- action:
  - data:
      brightness: '200'
      entity_id:
      - light.kitchen_light_right
      - light.kitchen_light_left
    service: light.turn_on
  alias: Kitchen Lights On (Day)
  condition:
  - below: '30.0'
    condition: numeric_state
    entity_id: sensor.garage_sensor_luminance
  - after: 05:00:00
    condition: time
  id: '1522788343645'
  trigger:
  - entity_id: binary_sensor.garage_sensor_sensor
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      brightness: '100'
      entity_id:
      - light.kitchen_light_right
      - light.kitchen_light_left
      transition: '30'
    service: light.turn_on
  alias: Kitchen Lights On (Night)
  condition:
  - before: 05:00
    condition: time
  id: '1522788647469'
  trigger:
  - entity_id: binary_sensor.garage_sensor_sensor
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: group.kitchen
    service: homeassistant.turn_off
  alias: Kitchen Lights Off
  condition: []
  id: '1522789372379'
  trigger:
  - entity_id: binary_sensor.garage_sensor_sensor
    from: 'on'
    platform: state
    to: 'off'
