homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 41.3984
  longitude: 2.1741
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 23
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: evanfloden.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

map:
        
# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Cloud
#cloud:

# Weather prediction
sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - precip_probability
      - temperature
      - temperature_max
      - temperature_min
  - platform: template
    sensors:
      stairway_sensor_battery:
        value_template: >-
          {%- if states.zwave.stairway_sensor -%}
            {{ states.zwave.stairway_sensor.attributes.battery_level }}
          {%- else -%}
            N/A
          {%- endif -%}
        unit_of_measurement: '%'
  - platform: template
    sensors:
      lounge_sensor_battery:
        value_template: >-
          {%- if states.zwave.lounge_sensor -%}
            {{ states.zwave.lounge_sensor.attributes.battery_level }}
          {%- else -%}
            N/A
          {%- endif -%}
        unit_of_measurement: '%'
  - platform: template
    sensors:
      garage_sensor_battery:
        value_template: >-
          {%- if states.zwave.garage_sensor -%}
            {{ states.zwave.garage_sensor.attributes.battery_level }}
          {%- else -%}
            N/A
          {%- endif -%}
        unit_of_measurement: '%'
  - platform: template
    sensors:
      kitchen_smoke_sensor_battery:
        value_template: >-
          {%- if states.zwave.kitchen_smoke_sensor -%}
            {{ states.zwave.kitchen_smoke_sensor.attributes.battery_level }}
          {%- else -%}
            N/A
          {%- endif -%}
        unit_of_measurement: '%'
  - platform: template
    sensors:
      alarm_sensor_battery:
        value_template: >-
          {%- if states.zwave.alarm_keypad -%}
            {{ states.zwave.alarm_keypad.attributes.battery_level }}
          {%- else -%}
            N/A
          {%- endif -%}
        unit_of_measurement: '%'


# Device tracking
device_tracker:
- platform: owntracks_http
  new_device_defaults:
    track_new_devices: False
- platform: asuswrt
  host: 192.168.2.1
  username: !secret asuswrt_username
  password: !secret asuswrt_password
  interval_seconds: 10
  consider_home: 180
  new_device_defaults:
    track_new_devices: False

# Amazon Hue for Alexa 
emulated_hue:
  host_ip: 192.168.2.148
  off_maps_to_on_domains:
  exposed_domains:
    - script
    - switch
    - light
    - group
    - input_boolean
    - media_player
    - fan

# Text to speech
tts:
  - platform: google

# Z-wave
zwave:
  usb_path: /dev/ttyACM0
  
# IKEA Tradfri
tradfri:
  host: 192.168.2.172
  allow_tradfri_groups: false 

# Amcrest Camera
amcrest:
  host: 192.168.2.108
  username: !secret amcrest_username
  password: !secret amcrest_password
  sensors:
    - motion_detector
      #    - sdcard

#ffmpeg:

#camera:
#  - platform: ffmpeg
#    name: "Amcrest Baby Cam"
#    input: !secret amcrest_babycam_ffmpeg_url

switch:
  platform: command_line
  switches:
    vpn_tv:
      command_on: "ssh -i .ssh/id_rsa skptic@192.168.2.1 'service start_vpnclient2'"
      command_off: "ssh -i .ssh/id_rsa skptic@192.168.2.1 'service stop_vpnclient2'"
      friendly_name: Nord VPN Switch

climate:
  - platform: generic_thermostat
    name: Central Heating System
    heater: switch.central_heating_switch
    target_sensor: sensor.lounge_sensor_temperature
    min_cycle_duration:
      minutes: 5
    keep_alive:
      minutes: 15

# Media Devices
media_player:
  - platform: webostv
    host: 192.168.2.162
    name: Living Room TV  
    timeout: 5
    turn_on_action:
      service: persistent_notification.create
      data:
        message: "Turn on action"
    customize:
      sources:
        - livetv
        - youtube
        - hdmi1
        - hdmi2
        - 'Amazon Prime Video'
        - netflix
  - platform: spotify
    client_id: 7a72e572ba5241b08b484b5a85d7b036
    client_secret: !secret spotify_client

# Manual Alarm 
alarm_control_panel:
  - platform: manual
    disarm_after_trigger: true

# Notify Components
notify:
  - name: garage_speaker
    platform: lannouncer
    host: 192.168.2.20
  - platform: webostv
    host: 192.168.2.162
    name: lounge_tv
    icon: ha_favicon-192x192.png  
  - platform: pushbullet
    name: pushbullet
    api_key: !secret pushbullet_api_key

# Zones for location tracking
zone:
- name: Home
  latitude: 41.480439
  longitude: 2.321673
  radius: 200
  icon: mdi:home
- name: CRG
  latitude: 41.385221
  longitude: 2.194218
  radius: 200
  icon: mdi:flask-outline
- name: Besos
  latitude: 41.423956
  longitude: 2.230546
  radius: 200
  icon: mdi:tram
- name: Montgat
  latitude: 41.462978
  longitude: 2.272088
  radius: 200
  icon: mdi:tram

panel_iframe:
  terminal:
    title: Terminal
    icon: mdi:console
    url: https://floden.duckdns.org:7681

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
shell_command: !include shell_commands.yaml
